"""Add full recon job uniqueness

Revision ID: 49763e815377
Revises: f88da1a7885b
Create Date: 2026-09-02 22:38:29.911118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49763e815377'
down_revision: Union[str, Sequence[str], None] = 'f88da1a7885b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_full_recon_job', 'recon_jobs', ['target_id'], unique=True, sqlite_where=sa.text("job_type = 'full_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_full_recon_job', table_name='recon_jobs', sqlite_where=sa.text("job_type = 'full_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###
