"""enforce active recon job uniqueness

Revision ID: 4c6c517f1437
Revises: ae21d2324912
Create Date: 2026-09-01 20:35:16.568219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6c517f1437'
down_revision: Union[str, Sequence[str], None] = 'ae21d2324912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_subdomain_recon_job', 'recon_jobs', ['target_id'], unique=True, sqlite_where=sa.text("job_type = 'subdomain_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_subdomain_recon_job', table_name='recon_jobs', sqlite_where=sa.text("job_type = 'subdomain_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###
