"""Enforce one active recon job per target

Revision ID: 54271b9de9b8
Revises: 49763e815377
Create Date: 2026-09-02 23:41:30.907500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54271b9de9b8'
down_revision: Union[str, Sequence[str], None] = '49763e815377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_active_asset_recon_job'), table_name='recon_jobs', sqlite_where=sa.text("job_type = 'asset_recon' AND status IN ('queued', 'running')"))
    op.drop_index(op.f('uq_active_full_recon_job'), table_name='recon_jobs', sqlite_where=sa.text("job_type = 'full_recon' AND status IN ('queued', 'running')"))
    op.drop_index(op.f('uq_active_subdomain_recon_job'), table_name='recon_jobs', sqlite_where=sa.text("job_type = 'subdomain_recon' AND status IN ('queued', 'running')"))
    op.create_index('uq_active_recon_job', 'recon_jobs', ['target_id'], unique=True, sqlite_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_recon_job', table_name='recon_jobs', sqlite_where=sa.text("status IN ('queued', 'running')"))
    op.create_index(op.f('uq_active_subdomain_recon_job'), 'recon_jobs', ['target_id'], unique=1, sqlite_where=sa.text("job_type = 'subdomain_recon' AND status IN ('queued', 'running')"))
    op.create_index(op.f('uq_active_full_recon_job'), 'recon_jobs', ['target_id'], unique=1, sqlite_where=sa.text("job_type = 'full_recon' AND status IN ('queued', 'running')"))
    op.create_index(op.f('uq_active_asset_recon_job'), 'recon_jobs', ['target_id'], unique=1, sqlite_where=sa.text("job_type = 'asset_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###
