"""add subdomains table

Revision ID: 71827d48a883
Revises: bdcc38e98b4c
Create Date: 2026-08-18 20:12:12.850142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71827d48a883'
down_revision: Union[str, Sequence[str], None] = 'bdcc38e98b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subdomains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subdomains_id'), 'subdomains', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subdomains_id'), table_name='subdomains')
    op.drop_table('subdomains')
    # ### end Alembic commands ###
