"""add poc fields to findings

Revision ID: bdcc38e98b4c
Revises: 6d0a1442ee47
Create Date: 2026-08-15 02:00:34.242200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcc38e98b4c'
down_revision: Union[str, Sequence[str], None] = '6d0a1442ee47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('poc', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('poc_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'poc_type')
    op.drop_column('findings', 'poc')
    # ### end Alembic commands ###
