"""Add active asset recon job uniqueness

Revision ID: f88da1a7885b
Revises: e85f82e72147
Create Date: 2026-09-02 13:37:26.461984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f88da1a7885b'
down_revision: Union[str, Sequence[str], None] = 'e85f82e72147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_asset_recon_job', 'recon_jobs', ['target_id'], unique=True, sqlite_where=sa.text("job_type = 'asset_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_asset_recon_job', table_name='recon_jobs', sqlite_where=sa.text("job_type = 'asset_recon' AND status IN ('queued', 'running')"))
    # ### end Alembic commands ###
